# Generated by Django 5.2.1 on 2025-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (optional)', null=True, upload_to='profile_pictures', verbose_name='Profile Picture'),
        ),
    ]
