# Generated by Django 5.2.1 on 2025-06-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_course_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='specialty',
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main_app.semesterprogram'),
        ),
    ]
