# Generated by Django 5.2.3 on 2025-06-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_grade_teacher_remove_student_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='absences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main_app.semesterprogram'),
        ),
    ]
