# Generated by Django 5.2.1 on 2025-06-18 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_student_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterprogram',
            name='college',
        ),
        migrations.AddField(
            model_name='semesterprogram',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_programs', to='main_app.department'),
        ),
    ]
