# Generated by Django 5.2.1 on 2025-06-18 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_semesterprogram_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_faculty', to='main_app.teacher'),
        ),
    ]
